//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MemberForm()
        {
            this.MemberAstroDetail = new HashSet<MemberAstroDetail>();
            this.PwdForm = new HashSet<PwdForm>();
            this.ReserveForm = new HashSet<ReserveForm>();
        }
    
        public int mID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public string MemberName { get; set; }
        public Nullable<bool> MemberSex { get; set; }
        public Nullable<System.DateTime> MemberBirth { get; set; }
        public Nullable<System.TimeSpan> MemberBirthTime { get; set; }
        public string MemberBirthPlace { get; set; }
        public string MemberPhone { get; set; }
        public string MemberEmail { get; set; }
        public string MemberAccount { get; set; }
    
        public virtual Login平台 Login平台 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberAstroDetail> MemberAstroDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PwdForm> PwdForm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReserveForm> ReserveForm { get; set; }
    }
}
