//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OurAstroEntities : DbContext
    {
        public OurAstroEntities()
            : base("name=OurAstroEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Login平台> Login平台 { get; set; }
        public virtual DbSet<MemberAstroDetail> MemberAstroDetail { get; set; }
        public virtual DbSet<MemberForm> MemberForm { get; set; }
        public virtual DbSet<ProForm> ProForm { get; set; }
        public virtual DbSet<ProSkillList> ProSkillList { get; set; }
        public virtual DbSet<ReserveForm> ReserveForm { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TempForm> TempForm { get; set; }
    }
}
