//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProForm()
        {
            this.ReserveForm = new HashSet<ReserveForm>();
        }
    
        public int pID { get; set; }
        public Nullable<int> ProID { get; set; }
        public string ProName { get; set; }
        public Nullable<bool> ProSex { get; set; }
        public string ProExperience { get; set; }
        public string ProSkill { get; set; }
        public Nullable<decimal> ProCost { get; set; }
        public string ProSelect { get; set; }
        public string ProAddress { get; set; }
        public string ProPhone { get; set; }
        public string ProEmail { get; set; }
        public string ProPassword { get; set; }
        public string ProAccount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReserveForm> ReserveForm { get; set; }
    }
}
